apiVersion: v1
kind: Service
metadata:
  name: orders
  labels:
    app: orders
    part-of: microsvc
spec:
  type: ClusterIP
  selector:
    app: orders
  ports:
    - name: http
      port: 3000
      targetPort: 3000
