apiVersion: v1
kind: ServiceAccount
metadata:
  name: flask-eks
  namespace: flask-eks
  labels:
    app.kubernetes.io/name: flask-eks
    app.kubernetes.io/part-of: flask-eks
  # To use IRSA, annotate with an IAM role ARN provisioned via Terraform:
  # annotations:
  #   eks.amazonaws.com/role-arn: arn:aws:iam::<ACCOUNT_ID>:role/flask-eks-irsa
automountServiceAccountToken: true
